version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: doctriage-api
    ports:
      - "8181:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    environment:
      - MODEL_PATH=/app/outputs/distil-lora-4bit-20250521-115746
      - UPLOAD_DIR=/app/uploads
      - PYTHONPATH=/app
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctriage-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./src:/app/src
    environment:
      - API_URL=http://api:8000  # Internal Docker network still uses port 8000
      - PYTHONPATH=/app
    command: streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - api
  
  # Argilla setup with auto-login as annotator (runs Argilla v1.29.1)
  argilla:
    image: argilla/argilla-quickstart:latest
    container_name: doctriage-argilla
    ports:
      - "6900:6900"
    volumes:
      - argilla-data:/app/data
      - ./argilla_auto_login.js:/app/argilla_server/static/js/auto_login.js
    environment:
      - HF_TOKEN=no-token-needed-for-local-use
      - ARGILLA_API_KEY=argilla.apikey
      - ARGILLA_PASSWORD=12345678
      - TEAM_API_KEY=team.apikey
      - TEAM_PASSWORD=12345678
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6900"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

volumes:
  argilla-data: 