version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: doctriage-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    environment:
      - MODEL_PATH=/app/outputs/distil-lora-4bit
      - UPLOAD_DIR=/app/uploads
      - PYTHONPATH=/app
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctriage-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./src:/app/src
    environment:
      - API_URL=http://api:8000
      - PYTHONPATH=/app
    command: streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - api
  
  argilla:
    image: argilla/argilla-server:latest
    container_name: doctriage-argilla
    ports:
      - "6900:6900"
    environment:
      - ARGILLA_HOME_PATH=/argilla
      - ARGILLA_SERVER_HOST=0.0.0.0
      - ARGILLA_SERVER_PORT=6900
    volumes:
      - argilla-data:/argilla
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6900/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  argilla-data: 